### PR TITLE
Presentations

### PR DESCRIPTION
**Pull request by TomMaullin**
I have now completed an initial version of the presentations section of the website in order to address issue #6 . I have done this in a way such that presentations can be easily added to and removed from the website without the user touching the HTML. Full details of this can be found in the Readme.md file. 

If possible, @nicholst could you try running the presentations section on a mac and see whether you are able to add and remove presentations from the website using the instructions in the Readme.md?

### CODE REVIEW

**Comment by nicholst** [comment]
@TomMaullin - I'll take a look, but remind me how I preview this?  I.e. I know how to look at master, but how do I get a HTML preview of a branch?

**Comment by TomMaullin** [comment]
Hi Tom,

To get a preview I make a local copy of the branch and then from command
line run the following commands:

1) `make` (this generates the publications and presentations pages)
2) `jekyll serve -w` (this then runs the localhost - the commandline should
then tell you the server address to visit in your browser)

You will need to install the prerequisites listed in the readme though if
you haven't already. Let me know if you have any further problems.

Cheers,
Tom M

**Comment by nicholst** [comment]
Thanks for the tips Tom... I can now review all your stuff with some combination of 
```
git remote add Toms git@github.com:/TomMaullin/NISOx-BDI.github.io
git fetch Toms
git checkout Toms/presentations
```

**Comment by nicholst** [comment]
A few things here:

- [ ] `presentations/OHBM2009` has only the stub for Imgen2009, [original](http://warwick.ac.uk/tenichols/presentations/ohbm2009) also has a poster.
- [ ] `presentations/OHBM2009/Imgen2009` has only one talk on my version (after make), while the [original](http://warwick.ac.uk/tenichols/presentations/ohbm2009/imggen) has 5 talks
- [ ] On [2010 Applied Neuroimaging Course](https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/nichols/presentations/appneuroimg-2010/) two issues... it seems that many of the slides are missing, and I must admit I miss the content there (i.e. the whole time lines with the readings).  What do you think? one thing is that we could simply make a PDF document that is a rendering of that HTML, holding links to the non-presentations).  Do you have any ideas?
- [ ] OHBM 2010 is also missing some stuff

I'll stop here... I think the YAML file must be incomplete.

**Comment by nicholst** [comment]
I haven't tried to edit any of the YAML files, but I looked at the Readme.md and it's very clear!  I think I could do it easily.  (Just don't have time now).

**Comment by TomMaullin** [comment]
Hi @nicholst , 

Just to quickly address the issue of the missing files in the YAML; if I remember correctly whilst these files are listed on the old website they all lead to either corrupted files or non-existent links. We did discuss around a month ago in an email thread named `Corrupted and Missing presentations` where I have listed all missing presentations. If you have any copies of the missing and/or corrupted presentations and wish to upload them please send them to me and I'll sort that ASAP - with the YAML script this shouldn't take too long.

**Comment by nicholst** [comment]
Ah... sorry, I forgot.

Hopefully not contradicting what I said then:  Can you create 'stubs', i.e.
that list the talk/event and the title but then have no link?  I can then
try to fill in the PDFs later.

**Comment by TomMaullin** [comment]
Hi @nicholst 

I have now added the requested stubs and regarding the timeline issue, I have added an option in the YAML to list the times with the presentations also (see the OHBM 2010 Imaging genetics page) so we don't lose the original schedule. Let me know what you think and if you have any further feedback!

**Comment by nicholst** [comment]
Hi Tom,

Either I've messed up something or something is broke.

I've pulled your latest branch, and now when I run the website preview there are basically *no* presentations.  

Here's what I did:
```
git pull Toms presentations
make cean
make all
jekyll serve -w 
```
I got one error (`Build Warning: Layout 'nil' requested in blog/blog.xml does not exist.
`) but I wasn't going to worry about that since this is about the presentations.

But now when I click on any link I get 404.  E.g. `http://127.0.0.1:4000/presentations/OHBM2009/` is now not found.  And, correspondingly, there is no true under either presentations/ or _site/presentations.

This is the last commit I have which I think makes me current, no?
```
commit 99c0489acfb562d1a497934fcb151c62008ad451
Author: Tom Maullin <tommaullin@gmail.com>
Date:   Fri Nov 3 13:39:11 2017 +0000
```
Any ideas?

**Comment by TomMaullin** [comment]
Hi Tom,

Hmm... that's strange... my first thought is maybe the makefile thinks
everything is up to date for some reason. This sometimes happens when I
first start a branch. Try adding a space somewhere in talks.yml and save it
and see if make now recreates the presentations.

Let me know if that works and if not let me know what printed error you get.

Cheers,
Tom M

On 4 Nov 2017 08:08, "Thomas Nichols" <notifications@github.com> wrote:

Hi Tom,

Either I've messed up something or something is broke.

I've pulled your latest branch, and now when I run the website preview
there are basically *no* presentations.

Here's what I did:

git pull Toms presentations
make cean
make all
jekyll serve -w

I got one error (Build Warning: Layout 'nil' requested in blog/blog.xml
does not exist.) but I wasn't going to worry about that since this is about
the presentations.

But now when I click on any link I get 404. E.g. http://127.0.0.1:4000/
presentations/OHBM2009/ is now not found. And, correspondingly, there is no
true under either presentations/ or _site/presentations.

This is the last commit I have which I think makes me current, no?

commit 99c0489acfb562d1a497934fcb151c62008ad451
Author: Tom Maullin <tommaullin@gmail.com>
Date:   Fri Nov 3 13:39:11 2017 +0000

Any ideas?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NISOx-BDI/NISOx-BDI.github.io/pull/14#issuecomment-341879662>,
or mute the thread

**Comment by TomMaullin** [comment]
Oh actually - I've just noticed you have a typo - you say 'make cean' not
'make clean' - could this be the cause?

Cheers,
Tom M

**Comment by nicholst** [comment]
Got it! ` touch _data/talks.yml` did the job!

**Comment by TomMaullin** [comment]
Ah yes! That's probably better than my suggestion of adding a space to the
file!

Cheers,
Tom M


On 4 Nov 2017 12:30, "Thomas Nichols" <notifications@github.com> wrote:

Got it! ` touch _data/talks.yml` did the job!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NISOx-BDI/NISOx-BDI.github.io/pull/14#issuecomment-341893284>,
or mute the thread

**Comment by TomMaullin** [comment]
Hi @nicholst, am I good to merge this branch?

**Comment by nicholst** [comment]
Sorry for the delay.  I'm again having problems here.  I am on your presentations branch, and when I do make clean; make it works (i.e. Make runs fine) but I have no presentations...
```
ls -l presentations
total 16
-rw-r--r--  1 nichols  staff  6675  9 Nov 10:37 index.html
-rw-r--r--  1 nichols  staff  4451  9 Nov 10:37 presGen.py
```

and I get 404 when I try to navigate (of course) into any of them.

**Comment by TomMaullin** [comment]
Can you confirm for me whether or not the following works:

`make clean`
` touch _data/talks.yml`
`make`

If so I will add the touch command into the makefile.

**Pull request merged**
