### PR TITLE
Software

### PR DESCRIPTION
**Pull request by TomMaullin**
Hi @nicholst ,

I have now migrated all software pages as needed to close issue #11 . There are a few footnotes though:

* I couldn't think of a way to automate this like with the presentations and publications so I have had to move over every page manually. I have checked all images, mailing references, references to warwick, urls and pdfs exhaustively but there is a lot on there so it might be worth having someone play around with the pages to try and find anything broken or incorrect.

* For the form registration I have presented two alternatives. 
  * The first service is formspree.io. This is the one that's currently being used on this branch (see `software/snpm13/snpmreg` for an example). This form emails whoever is behind the website if someone completes it and then redirects to a download url. I'd suggest we use this as it looks good, redirects to a download URL and has a robot CAPTCHA feature when you submit. The downside is, we can't get any summary statistics from this service.
  * The second is google forms. I've included a form here just for comparison. If you go to `software/temp` on the website you will find an embedded google form. The problem with google forms is that they are very restricted in how you can make them look and you can't redirect to a download URL once you have submitted. The only reason I've included these forms as an option is that you can get summary statistics, pi charts etc from this service. I believe this is probably the only realistic way to address issue #12, as the github API requires authentication and I can't find a form service that offers both summary statistics and a nice display.

Please let me know if you have any feedback/suggestions or if anything seems out of place.

### CODE REVIEW

**Comment by nicholst** [comment]
Thanks Tom!

As discussed, please implement the Google option via a link (i.e. no page
embedding is needed).

-Tom

**Comment by TomMaullin** [comment]
Hi @nicholst 

The form we discussed has now been added! Please let me know if there is any further feedback! Else I believe we are good to merge!

**Comment by nicholst** [comment]
Just went to look at the PR, did make clean; make and I'm still getting killed by `@makedir` in "https://github.com/TomMaullin/NISOx-BDI.github.io/blob/software/Makefile#L13

I thought you had a fix for this?

**Comment by TomMaullin** [comment]
I have fixed the make problem but on the publications branch we last merged. I haven't updated that in this branch as this branch does not require the make function to run the software pages. All you need do to view the changes on this branch is run `jekyll serve -w`.

The issue of the make function would be resolved when the branch is merged.

**Pull request merged**
